datasets:
  feature_face_caption:
    data_type: images
    task_pool: [emotion]
    annotation_format: auto
    
    build_info:
      image_path: /home/czb/big_space/datasets/Emotion/MER2023/video

      ann_path: /home/user/selected_face/face_emotion/relative_train_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/MERR_coarse_grained.txt
      # ann_path: /home/user/selected_face/face_emotion/MERR_fine_grained.txt

      transcription_path: transcription_en_all.csv
      coarse_grained_json_path: MERR_coarse_grained.json
      fine_grained_json_path: MERR_fine_grained.json
      face_feature_path: mae_340_UTT
      video_feature_path: maeV_399_UTT
      audio_feature_path: HL-UTT
