# Site settings
title: Emotion-LLaMA
description: Multimodal Emotion Recognition and Reasoning with Instruction Tuning
baseurl: "/Emotion-LLaMA/docs"
url: "https://zebangcheng.github.io"

# Repository
repository: ZebangCheng/Emotion-LLaMA

# Theme (works both locally and on GitHub Pages)
remote_theme: just-the-docs/just-the-docs@v0.8.2

# Color scheme
color_scheme: light

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Heading anchor links
heading_anchors: true

# Aux links
aux_links:
  "GitHub Repository":
    - "https://github.com/ZebangCheng/Emotion-LLaMA"
  "Paper (arXiv)":
    - "https://arxiv.org/pdf/2406.11161"
  "Online Demo":
    - "https://huggingface.co/spaces/ZebangCheng/Emotion-LLaMA"

# Aux links in new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2024 Emotion-LLaMA. Distributed under the <a href=\"https://github.com/ZebangCheng/Emotion-LLaMA/blob/main/LICENSE.md\">BSD 3-Clause License</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable/disable copy button on code
enable_copy_code_button: true

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# kramdown settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections for organizing content
collections_dir: collections

# Plugin settings
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

