source "https://rubygems.org"

# Core Jekyll
gem "jekyll", "~> 4.3.0"

# Just the Docs theme dependencies
gem "rake", "~> 13.0"
gem "webrick", "~> 1.7"

# Essential plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-remote-theme", "~> 0.4"
  gem "jekyll-include-cache", "~> 0.2"
end
